# serverless.yml

service: my-express-site

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-2

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /api/getUsername
          method: get
          cors: true